// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_TextEditor_H
#define WINRT_TextEditor_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260520.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260520.1"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/TextEditor.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_TextEditor_IMainWindow<D>::MyProperty() const
    {
        std::int32_t value{};
        consume_general<winrt::TextEditor::IMainWindow, D>(static_cast<D const*>(this), &abi_t<winrt::TextEditor::IMainWindow>::get_MyProperty, &value);
        return value;
    }
    template <typename D> auto consume_TextEditor_IMainWindow<D>::MyProperty(std::int32_t value) const
    {
        consume_general<winrt::TextEditor::IMainWindow, D>(static_cast<D const*>(this), &abi_t<winrt::TextEditor::IMainWindow>::put_MyProperty, value);
    }
    template <typename D>
    struct produce<D, winrt::TextEditor::IMainWindow> : produce_base<D, winrt::TextEditor::IMainWindow>
    {
        std::int32_t __stdcall get_MyProperty(std::int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<std::int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall put_MyProperty(std::int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::TextEditor
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::TextEditor::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::TextEditor::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::TextEditor::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
