// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_TextEditor_H
#define WINRT_TextEditor_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260520.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260520.1"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/TextEditor.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D>
    struct produce<D, winrt::TextEditor::IMainWindow> : produce_base<D, winrt::TextEditor::IMainWindow>
    {
    };
}
WINRT_EXPORT namespace winrt::TextEditor
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::TextEditor::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::TextEditor::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::TextEditor::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
