// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifdef WINRT_IMPORT_MODULE
#include "winrt/base_macros.h"
import winrt.Microsoft.UI.Xaml;
import winrt.TextEditor;
#else // WINRT_IMPORT_MODULE
#include "winrt/Microsoft.UI.Xaml.h"
#include "winrt/TextEditor.h"
#endif // WINRT_IMPORT_MODULE
namespace winrt::TextEditor::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MainWindow_base : implements<D, TextEditor::MainWindow, composing, I...>,
        impl::require<D, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>,
        impl::base<D, winrt::Microsoft::UI::Xaml::Window>
    {
        using base_type = MainWindow_base;
        using class_type = TextEditor::MainWindow;
        using implements_type = typename MainWindow_base::implements_type;
        using implements_type::implements_type;
        using composable_base = winrt::Microsoft::UI::Xaml::Window;
        hstring GetRuntimeClassName() const override
        {
            return L"TextEditor.MainWindow";
        }
        MainWindow_base()
        {
            impl::call_factory<winrt::Microsoft::UI::Xaml::Window, winrt::Microsoft::UI::Xaml::IWindowFactory>([&](winrt::Microsoft::UI::Xaml::IWindowFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
}
namespace winrt::TextEditor::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES MainWindowT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = TextEditor::MainWindow;

        hstring GetRuntimeClassName() const
        {
            return L"TextEditor.MainWindow";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_MAINWINDOW_XAML_G_H) || __has_include("MainWindow.xaml.g.h")

#include "MainWindow.xaml.g.h"

#else

namespace winrt::TextEditor::implementation
{
    template <typename D, typename... I>
    using MainWindowT = MainWindow_base<D, I...>;
}

#endif
