// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

void* winrt_make_TextEditor_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::TextEditor::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::TextEditor
{
    MainWindow::MainWindow() :
        MainWindow(make<TextEditor::implementation::MainWindow>())
    {
    }
}
