// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

void* winrt_make_TextEditor_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::TextEditor::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::TextEditor
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<TextEditor::implementation::XamlMetaDataProvider>())
    {
    }
}
