// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_TextEditor_0_H
#define WINRT_TextEditor_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::TextEditor
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
WINRT_EXPORT namespace winrt::impl
{
    template <> struct category<winrt::TextEditor::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::TextEditor::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::TextEditor::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::TextEditor::MainWindow> = L"TextEditor.MainWindow";
    template <> inline constexpr auto& name_v<winrt::TextEditor::XamlMetaDataProvider> = L"TextEditor.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::TextEditor::IMainWindow> = L"TextEditor.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::TextEditor::IMainWindow>{ 0xC8878129,0xC7BA,0x5555,{ 0x86,0x36,0x05,0x0E,0xA8,0x31,0xB2,0xDA } }; // C8878129-C7BA-5555-8636-050EA831B2DA
    template <> struct default_interface<winrt::TextEditor::MainWindow>{ using type = winrt::TextEditor::IMainWindow; };
    template <> struct default_interface<winrt::TextEditor::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::TextEditor::IMainWindow>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_TextEditor_IMainWindow
    {
    };
    template <> struct consume<winrt::TextEditor::IMainWindow>
    {
        template <typename D> using type = consume_TextEditor_IMainWindow<D>;
    };
}
#endif
