// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_TextEditor_0_H
#define WINRT_TextEditor_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::TextEditor
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
WINRT_EXPORT namespace winrt::impl
{
    template <> struct category<winrt::TextEditor::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::TextEditor::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::TextEditor::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::TextEditor::MainWindow> = L"TextEditor.MainWindow";
    template <> inline constexpr auto& name_v<winrt::TextEditor::XamlMetaDataProvider> = L"TextEditor.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::TextEditor::IMainWindow> = L"TextEditor.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::TextEditor::IMainWindow>{ 0xE9787942,0xA603,0x5E64,{ 0xBB,0xF9,0x5E,0x75,0x96,0x9C,0x85,0x7A } }; // E9787942-A603-5E64-BBF9-5E75969C857A
    template <> struct default_interface<winrt::TextEditor::MainWindow>{ using type = winrt::TextEditor::IMainWindow; };
    template <> struct default_interface<winrt::TextEditor::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::TextEditor::IMainWindow>
    {
        struct WINRT_IMPL_ABI_DECL type : inspectable_abi
        {
            virtual std::int32_t __stdcall get_MyProperty(std::int32_t*) noexcept = 0;
            virtual std::int32_t __stdcall put_MyProperty(std::int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_TextEditor_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(std::int32_t value) const;
    };
    template <> struct consume<winrt::TextEditor::IMainWindow>
    {
        template <typename D> using type = consume_TextEditor_IMainWindow<D>;
    };
}
#endif
